name: Deploy Snowflake Changes

on:
  workflow_dispatch:  # Triggered manually, change this if you want auto triggers.

jobs:
  deploy-snowflake-changes-job:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Step 3: Install dependencies (e.g., schemachange)
      - name: Install dependencies
        run: |
          pip install schemachange

      # Step 4: Set up Snowflake credentials and run schemachange
      - name: Run schemachange
        env:
          SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}  # Snowflake Account - Add this as a secret in GitHub
          SF_USERNAME: ${{ secrets.SF_USERNAME }}  # Snowflake Username - Add this as a secret in GitHub
          SF_ROLE: ${{ secrets.SF_ROLE }}  # Snowflake Role - Add this as a secret in GitHub
          SF_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}  # Snowflake Warehouse - Add this as a secret in GitHub
          SF_DATABASE: ${{ secrets.SF_DATABASE }}  # Snowflake Database - Add this as a secret in GitHub
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}  # Snowflake Password - Add this as a secret in GitHub
          GITHUB_WORKSPACE: ${{ github.workspace }}
        run: |
          # Output current workspace and Python version
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          python --version
          
          # Installing schemachange (if not already installed)
          echo "Step 1: Installing schemachange"
          pip install schemachange
          
          # Running schemachange to deploy changes
          echo "Step 2: Running schemachange"
          schemachange -f $GITHUB_WORKSPACE/deploy -a $SF_ACCOUNT -u $SF_USERNAME -r $SF_ROLE -w $SF_WAREHOUSE -d $SF_DATABASE -c $SF_DATABASE.SCHEMACHANGE.CHANGE_HISTORY --create-change-history-table
